/*******************************************************************************
* Copyright (C) 2016-2021 Advanced Micro Devices, Inc. All rights reserved.
*
* Permission is hereby granted, free of charge, to any person obtaining a copy
* of this software and associated documentation files (the "Software"), to deal
* in the Software without restriction, including without limitation the rights
* to use, copy, modify, merge, publish, distribute, sublicense, and/or sell cop-
* ies of the Software, and to permit persons to whom the Software is furnished
* to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in all
* copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IM-
* PLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
* FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
* COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
* IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNE-
* CTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*******************************************************************************/

/**************************************************
* This file was generated by Tensile:             *
* https://github.com/ROCmSoftwarePlatform/Tensile *
**************************************************/


#include "/root/Tensile/build/1_BenchmarkProblems/Cij_Aik_Bkj_S_00/00_Final/source/Cij_Aik_Bkj_S_MT64x64x4_SN_K1_SVW2_WGM1.h"

#include "Cij_Aik_Bkj_S_MT64x64x4_SN_K1_SVW2_WGM1.h"



  /******************************************/
  /* Function Prefix                        */
  /******************************************/



/* tile parameters */
#define NUM_THREADS 256
#define SG0I 8
#define SG1J 8
#define TT0I 8
#define TT1J 8
#define MT0I (SG0I*TT0I)
#define MT1J (SG1J*TT1J)
#define VECTOR_WIDTH 4
#define GLOBAL_LOAD_VECTOR_WIDTH_A 1
#define GLOBAL_LOAD_VECTOR_WIDTH_B 1
#define GLOBAL_WRITE_VECTOR_WIDTH 4

/* DepthU parameters*/
#define CPSV (NUM_THREADS / MT0I * VECTOR_WIDTH)
#define LOCAL_SPLITU 4
#define UNROLL 1
#define LOCAL_DEPTHU (LOCAL_SPLITU*UNROLL)

/* other */
#define PAD 0
#define WORK_GROUP_MAPPING 1

/* num loads parallel and perpendicular to coalesced */
#define NLCA 1
#define NLCB 1
#define NLPA 1
#define NLPB 1

/* load sizes parallel and perpendicular to coalesced */
#define LSCA (MT0I/NLCA)
#define LSPA (LOCAL_DEPTHU/NLPA)
#define LSCB (LOCAL_DEPTHU/NLCB)
#define LSPB (MT1J/NLPB)
#define LVCA (LSCA/GLOBAL_LOAD_VECTOR_WIDTH_A)
#define LVCB (LSCB/GLOBAL_LOAD_VECTOR_WIDTH_B)
#define LVPA (LSPA/GLOBAL_LOAD_VECTOR_WIDTH_A)
#define LVPB (LSPB/GLOBAL_LOAD_VECTOR_WIDTH_B)
#define LDS_OFFSET_B 256
#define LDS_NUM_ELEMENTS 16384

/* global memory indices */
#define GLOBAL_D(IDX0I, IDX1J) (( ((int64_t)IDX0I)*strideD0I + ((int64_t)IDX1J)*strideD1J ))
#define GLOBAL_C(IDX0I, IDX1J) (( ((int64_t)IDX0I)*strideC0I + ((int64_t)IDX1J)*strideC1J ))
#define GLOBAL_OFFSET_A(IDX0I, IDXK) (( ((int64_t)IDX0I)*strideA0I + ((int64_t)IDXK)*strideAK ))
#define GLOBAL_OFFSET_B(IDXK, IDX1J) (( ((int64_t)IDXK)*strideBK + ((int64_t)IDX1J)*strideB1J ))

/* data types */
#define DATA_TYPE float
#define DEST_DATA_TYPE float
#define COMPUTE_DATA_TYPE float
#define MAGIC_DIV1(dividend, magicNumber, magicShift) ((uint64_t)(dividend) * magicNumber >> magicShift)

/* MAC's */
#define MAC(A,B,DST) DST += A*B
#define TYPE_MAC(MULA,MULB,DST) DST = MAC(MULA,MULB,DST);
#define TYPE_MAC_WRITE(DST,ALPHA,REG) DST = (ALPHA)*(REG);

/* 8x8 micro-tile */
#define MAC_8x8\
  TYPE_MAC(rA[0],rB[0],rC[0+0*TT0I]); \
  TYPE_MAC(rA[1],rB[0],rC[1+0*TT0I]); \
  TYPE_MAC(rA[2],rB[0],rC[2+0*TT0I]); \
  TYPE_MAC(rA[3],rB[0],rC[3+0*TT0I]); \
  TYPE_MAC(rA[4],rB[0],rC[4+0*TT0I]); \
  TYPE_MAC(rA[5],rB[0],rC[5+0*TT0I]); \
  TYPE_MAC(rA[6],rB[0],rC[6+0*TT0I]); \
  TYPE_MAC(rA[7],rB[0],rC[7+0*TT0I]); \
  TYPE_MAC(rA[0],rB[1],rC[0+1*TT0I]); \
  TYPE_MAC(rA[1],rB[1],rC[1+1*TT0I]); \
  TYPE_MAC(rA[2],rB[1],rC[2+1*TT0I]); \
  TYPE_MAC(rA[3],rB[1],rC[3+1*TT0I]); \
  TYPE_MAC(rA[4],rB[1],rC[4+1*TT0I]); \
  TYPE_MAC(rA[5],rB[1],rC[5+1*TT0I]); \
  TYPE_MAC(rA[6],rB[1],rC[6+1*TT0I]); \
  TYPE_MAC(rA[7],rB[1],rC[7+1*TT0I]); \
  TYPE_MAC(rA[0],rB[2],rC[0+2*TT0I]); \
  TYPE_MAC(rA[1],rB[2],rC[1+2*TT0I]); \
  TYPE_MAC(rA[2],rB[2],rC[2+2*TT0I]); \
  TYPE_MAC(rA[3],rB[2],rC[3+2*TT0I]); \
  TYPE_MAC(rA[4],rB[2],rC[4+2*TT0I]); \
  TYPE_MAC(rA[5],rB[2],rC[5+2*TT0I]); \
  TYPE_MAC(rA[6],rB[2],rC[6+2*TT0I]); \
  TYPE_MAC(rA[7],rB[2],rC[7+2*TT0I]); \
  TYPE_MAC(rA[0],rB[3],rC[0+3*TT0I]); \
  TYPE_MAC(rA[1],rB[3],rC[1+3*TT0I]); \
  TYPE_MAC(rA[2],rB[3],rC[2+3*TT0I]); \
  TYPE_MAC(rA[3],rB[3],rC[3+3*TT0I]); \
  TYPE_MAC(rA[4],rB[3],rC[4+3*TT0I]); \
  TYPE_MAC(rA[5],rB[3],rC[5+3*TT0I]); \
  TYPE_MAC(rA[6],rB[3],rC[6+3*TT0I]); \
  TYPE_MAC(rA[7],rB[3],rC[7+3*TT0I]); \
  TYPE_MAC(rA[0],rB[4],rC[0+4*TT0I]); \
  TYPE_MAC(rA[1],rB[4],rC[1+4*TT0I]); \
  TYPE_MAC(rA[2],rB[4],rC[2+4*TT0I]); \
  TYPE_MAC(rA[3],rB[4],rC[3+4*TT0I]); \
  TYPE_MAC(rA[4],rB[4],rC[4+4*TT0I]); \
  TYPE_MAC(rA[5],rB[4],rC[5+4*TT0I]); \
  TYPE_MAC(rA[6],rB[4],rC[6+4*TT0I]); \
  TYPE_MAC(rA[7],rB[4],rC[7+4*TT0I]); \
  TYPE_MAC(rA[0],rB[5],rC[0+5*TT0I]); \
  TYPE_MAC(rA[1],rB[5],rC[1+5*TT0I]); \
  TYPE_MAC(rA[2],rB[5],rC[2+5*TT0I]); \
  TYPE_MAC(rA[3],rB[5],rC[3+5*TT0I]); \
  TYPE_MAC(rA[4],rB[5],rC[4+5*TT0I]); \
  TYPE_MAC(rA[5],rB[5],rC[5+5*TT0I]); \
  TYPE_MAC(rA[6],rB[5],rC[6+5*TT0I]); \
  TYPE_MAC(rA[7],rB[5],rC[7+5*TT0I]); \
  TYPE_MAC(rA[0],rB[6],rC[0+6*TT0I]); \
  TYPE_MAC(rA[1],rB[6],rC[1+6*TT0I]); \
  TYPE_MAC(rA[2],rB[6],rC[2+6*TT0I]); \
  TYPE_MAC(rA[3],rB[6],rC[3+6*TT0I]); \
  TYPE_MAC(rA[4],rB[6],rC[4+6*TT0I]); \
  TYPE_MAC(rA[5],rB[6],rC[5+6*TT0I]); \
  TYPE_MAC(rA[6],rB[6],rC[6+6*TT0I]); \
  TYPE_MAC(rA[7],rB[6],rC[7+6*TT0I]); \
  TYPE_MAC(rA[0],rB[7],rC[0+7*TT0I]); \
  TYPE_MAC(rA[1],rB[7],rC[1+7*TT0I]); \
  TYPE_MAC(rA[2],rB[7],rC[2+7*TT0I]); \
  TYPE_MAC(rA[3],rB[7],rC[3+7*TT0I]); \
  TYPE_MAC(rA[4],rB[7],rC[4+7*TT0I]); \
  TYPE_MAC(rA[5],rB[7],rC[5+7*TT0I]); \
  TYPE_MAC(rA[6],rB[7],rC[6+7*TT0I]); \
  TYPE_MAC(rA[7],rB[7],rC[7+7*TT0I]); \

/* hard-coded initial strides CD*/
/* hard-coded initial strides AB */
#define strideD0I 1
#define strideC0I 1
#define strideA0I 1
#define strideBK 1


  /******************************************/
  /* Begin Kernel                           */
  /******************************************/

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-parameter"
extern "C"
__global__ void
__launch_bounds__(256)
Cij_Aik_Bkj_S_MT64x64x4_SN_K1_SVW2_WGM1(
  float *D,
  float const * C,
  float const * A,
  float const * B,
  float const alpha,
  unsigned int const strideD1J,
  unsigned int const strideC1J,
  unsigned int const strideAK,
  unsigned int const strideB1J,
  unsigned int size0I,
  unsigned int size1J,
  unsigned int sizeK,
  unsigned int staggerUIterParm,
  unsigned int problemNumGroupTiles0,
  unsigned int problemNumGroupTiles1 )
#pragma clang diagnostic pop

 {


  /******************************************/
  /* Allocate Resources                     */
  /******************************************/

  unsigned int serial = hc_get_workitem_id(0);
  unsigned int sgId = serial / (SG0I*SG1J);
#define SCALAR_ZERO (float)(0)
#define SCALAR_OOB_DATA SCALAR_ZERO
  /* registers for MAC's */
  DEST_DATA_TYPE rC[TT0I*TT1J];
  DATA_TYPE rA[TT0I];
  DATA_TYPE rB[TT1J];

  /* registers for global->local */
  DATA_TYPE a_0_0_0_0;
  DATA_TYPE b_0_0_0_0;

  /* allocate local memory */
  __shared__ DATA_TYPE localMemory[LDS_NUM_ELEMENTS];

  typedef struct MagicStruct {unsigned M; int a; int s;} MagicStruct;
  const unsigned MAGIC_STRUCT_A = 0x80000000; // for extracting a-bit from shift kernarg
#define MAGIC_DIV2(dividend, magic) (((((uint64_t)(dividend) * magic.M) >> 32) + dividend*magic.a) >> magic.s)


  /******************************************/
  /* Local Read Addresses                   */
  /******************************************/


  /* local read addresses: tile assignments a/b */

  unsigned int lr0I = (serial % SG0I);
  unsigned int lr1J = (serial / SG0I) % SG1J;


  /* local read addresses: final offsets a */

  unsigned int localReadOffsetA = lr0I*VECTOR_WIDTH + sgId*(MT0I+PAD);


  /* local read addresses: final offsets b */

  unsigned int localReadOffsetB = lr1J*VECTOR_WIDTH + sgId*(MT1J+PAD) + LDS_OFFSET_B;


  /* local read addresses: declare addresses a */

  DATA_TYPE *localReadA;


  /* local read addresses: declare addresses b */

  DATA_TYPE *localReadB;



  /******************************************/
  /* Begin setupNewTile, isPap=False           */
  /******************************************/


  /* global read addresses: work-group */

  unsigned int wg0I = hc_get_group_id(0);
  unsigned int wg1J = hc_get_group_id(1);
  unsigned int nwg0I = hc_get_num_groups(0);
  unsigned int nwg1J = hc_get_num_groups(1);


  /* global read addresses: tile offset assignment a */

  unsigned int globalReadOffsetA0I = (serial%LVCA)*GLOBAL_LOAD_VECTOR_WIDTH_A + (wg0I)*MT0I;


  /* global read addresses: tile offset assignment b */

  unsigned int globalReadOffsetB1J = (serial/LVCB) + (wg1J)*MT1J;


  /* global read addresses: unroll assignment a */

  unsigned int globalReadOffsetAK = (serial/LVCA);


  /* global read addresses: unroll assignment b */

  unsigned int globalReadOffsetBK = (serial%LVCB)*GLOBAL_LOAD_VECTOR_WIDTH_B;


  /* global read addresses: tile offsets a */

  unsigned int flattenedOffsetA_0_0 = globalReadOffsetA0I + 0 + 0*LSCA;
  flattenedOffsetA_0_0 = (flattenedOffsetA_0_0 > (size0I-1)) ? (size0I-1):flattenedOffsetA_0_0;
  unsigned int globalReadOffsetA0I_0_0 = flattenedOffsetA_0_0;


  /* global read addresses: tile offsets b */

  unsigned int flattenedOffsetB_0_0 = globalReadOffsetB1J + 0 + 0*LSPB;
  flattenedOffsetB_0_0 = (flattenedOffsetB_0_0 > (size1J-1)) ? (size1J-1):flattenedOffsetB_0_0;
  unsigned int globalReadOffsetB1J_0_0 = flattenedOffsetB_0_0;


  /* global read addresses: unroll offsets a */

  unsigned int globalReadOffsetAK_0_0 = globalReadOffsetAK + 0 + 0*LSPA;


  /* global read addresses: unroll offsets b */

  unsigned int globalReadOffsetBK_0_0 = globalReadOffsetBK + 0 + 0*LSCB;


  /* global read addresses: final offsets a */

  int64_t globalReadOffsetA_0_0_0_0 = GLOBAL_OFFSET_A( (globalReadOffsetA0I_0_0), (globalReadOffsetAK_0_0) );


  /* global read addresses: final offsets b */

  int64_t globalReadOffsetB_0_0_0_0 = GLOBAL_OFFSET_B( (globalReadOffsetBK_0_0), (globalReadOffsetB1J_0_0) );


  /* global read addresses: addresses a */

  DATA_TYPE const *globalReadA_0_0_0_0 = A + globalReadOffsetA_0_0_0_0;


  /* global read addresses: addresses b */

  DATA_TYPE const *globalReadB_0_0_0_0 = B + globalReadOffsetB_0_0_0_0;


  /* global read addresses: increments a */

  int64_t globalReadIncAK = (int64_t)strideAK*LOCAL_DEPTHU;


  /* global read addresses: increments b */

  int64_t globalReadIncBK = (int64_t)strideBK*LOCAL_DEPTHU;


  /******************************************/
  /* Local Write Addresses                  */
  /******************************************/


  /* local write addresses: tile assignment A */
  unsigned int lwA0I = (serial%LVCA)*GLOBAL_LOAD_VECTOR_WIDTH_A;


  /* local write addresses: tile assignment B */
  unsigned int lwB1J = (serial/LVCB);


  /* local write addresses: unroll assignment A */
  unsigned int lwAK = (serial/LVCA);


  /* local write addresses: unroll assignment B */
  unsigned int lwBK = (serial%LVCB)*GLOBAL_LOAD_VECTOR_WIDTH_B;


  /* local write addresses: first offset a */

  unsigned int localWriteFirstOffsetA = lwA0I + lwAK*(MT0I+PAD);


  /* local write addresses: first offset b */

  unsigned int localWriteFirstOffsetB = lwB1J + lwBK*(MT1J+PAD) + LDS_OFFSET_B;


  /* local write addresses: final offsets A */
  unsigned int localWriteOffsetA_0_0_0_0 = localWriteFirstOffsetA + (0 + 0*LSCA) + (0 + 0*LSPA)*(MT0I+PAD);


  /* local write addresses: final offsets B */
  unsigned int localWriteOffsetB_0_0_0_0 = localWriteFirstOffsetB + (0 + 0*LSCB)*(MT1J+PAD) + (0 + 0*LSPB);


  /* local write addresses: declare addresses A */
  DATA_TYPE *localWriteA_0_0_0_0;


  /* local write addresses: declare addresses B */
  DATA_TYPE *localWriteB_0_0_0_0;


  /* local write init pointers A */
  localWriteA_0_0_0_0 = (DATA_TYPE *)(localMemory + localWriteOffsetA_0_0_0_0);


  /* local write init pointers B */
  localWriteB_0_0_0_0 = (DATA_TYPE *)(localMemory + localWriteOffsetB_0_0_0_0);

  /* declare loop num iterations */

  int numIterK;


  rC[0] = SCALAR_ZERO;
  rC[1] = SCALAR_ZERO;
  rC[2] = SCALAR_ZERO;
  rC[3] = SCALAR_ZERO;
  rC[4] = SCALAR_ZERO;
  rC[5] = SCALAR_ZERO;
  rC[6] = SCALAR_ZERO;
  rC[7] = SCALAR_ZERO;
  rC[8] = SCALAR_ZERO;
  rC[9] = SCALAR_ZERO;
  rC[10] = SCALAR_ZERO;
  rC[11] = SCALAR_ZERO;
  rC[12] = SCALAR_ZERO;
  rC[13] = SCALAR_ZERO;
  rC[14] = SCALAR_ZERO;
  rC[15] = SCALAR_ZERO;
  rC[16] = SCALAR_ZERO;
  rC[17] = SCALAR_ZERO;
  rC[18] = SCALAR_ZERO;
  rC[19] = SCALAR_ZERO;
  rC[20] = SCALAR_ZERO;
  rC[21] = SCALAR_ZERO;
  rC[22] = SCALAR_ZERO;
  rC[23] = SCALAR_ZERO;
  rC[24] = SCALAR_ZERO;
  rC[25] = SCALAR_ZERO;
  rC[26] = SCALAR_ZERO;
  rC[27] = SCALAR_ZERO;
  rC[28] = SCALAR_ZERO;
  rC[29] = SCALAR_ZERO;
  rC[30] = SCALAR_ZERO;
  rC[31] = SCALAR_ZERO;
  rC[32] = SCALAR_ZERO;
  rC[33] = SCALAR_ZERO;
  rC[34] = SCALAR_ZERO;
  rC[35] = SCALAR_ZERO;
  rC[36] = SCALAR_ZERO;
  rC[37] = SCALAR_ZERO;
  rC[38] = SCALAR_ZERO;
  rC[39] = SCALAR_ZERO;
  rC[40] = SCALAR_ZERO;
  rC[41] = SCALAR_ZERO;
  rC[42] = SCALAR_ZERO;
  rC[43] = SCALAR_ZERO;
  rC[44] = SCALAR_ZERO;
  rC[45] = SCALAR_ZERO;
  rC[46] = SCALAR_ZERO;
  rC[47] = SCALAR_ZERO;
  rC[48] = SCALAR_ZERO;
  rC[49] = SCALAR_ZERO;
  rC[50] = SCALAR_ZERO;
  rC[51] = SCALAR_ZERO;
  rC[52] = SCALAR_ZERO;
  rC[53] = SCALAR_ZERO;
  rC[54] = SCALAR_ZERO;
  rC[55] = SCALAR_ZERO;
  rC[56] = SCALAR_ZERO;
  rC[57] = SCALAR_ZERO;
  rC[58] = SCALAR_ZERO;
  rC[59] = SCALAR_ZERO;
  rC[60] = SCALAR_ZERO;
  rC[61] = SCALAR_ZERO;
  rC[62] = SCALAR_ZERO;
  rC[63] = SCALAR_ZERO;


  /* Compute summation loop num iter */
  if(alpha == (float)(0)) sizeK = 0;  // Short circuit check alpha=0, skip A*B 
  numIterK = sizeK / LOCAL_DEPTHU;

  const unsigned origNumIter = numIterK;
  unsigned staggerUIter = (wg0I & staggerUIterParm);
  staggerUIter = (staggerUIter << 4); // shift so each stagger has 256-byte stride

  globalReadA_0_0_0_0 += (staggerUIter * globalReadIncAK); // apply stagger offset


  globalReadB_0_0_0_0 += (staggerUIter * globalReadIncBK); // apply stagger offset

  staggerUIter += 0; // add PrefetchGlobalRead

  /* local read addresses: init pointers a */

  localReadA = (DATA_TYPE *)(localMemory + localReadOffsetA);

  /* local read addresses: init pointers b */

  localReadB = (DATA_TYPE *)(localMemory + localReadOffsetB);


  /******************************************/
  /* End setupNewTile, isPap=False             */
  /******************************************/


  /******************************************/
  /* Unrolled Loop(s) - Begin               */
  /******************************************/

  while (numIterK-- > 0) {


    /******************************************/
    /* Unrolled Loop 1/1 - Begin              */
    /******************************************/



    /* Begin Each Unroll: Check VGPR.checkin for INT8 LW */


    /* global read A */
    a_0_0_0_0 = *(globalReadA_0_0_0_0 + 0);

    /* global read B */
    b_0_0_0_0 = *(globalReadB_0_0_0_0 + 0);

    /* global read inc A for sumK */
    globalReadA_0_0_0_0 = (DATA_TYPE const *)( ((DATA_TYPE const *)globalReadA_0_0_0_0) + 1*globalReadIncAK);
    if ((numIterK) == staggerUIter) {
      globalReadA_0_0_0_0 -= (origNumIter * globalReadIncAK); // wrap staggered offset back to row start
    }

    /* global read inc B for sumK */
    globalReadB_0_0_0_0 = (DATA_TYPE const *)( ((DATA_TYPE const *)globalReadB_0_0_0_0) + 1*globalReadIncBK);
    if ((numIterK) == staggerUIter) {
      globalReadB_0_0_0_0 -= (origNumIter * globalReadIncBK); // wrap staggered offset back to row start
    }


    __syncthreads(); //PGR=0, prior iter done reading lds


    /* local write a */

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wconditional-uninitialized"
    *(localWriteA_0_0_0_0 + 0) = a_0_0_0_0;
#pragma clang diagnostic pop


    /* local write b */

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wconditional-uninitialized"
    *(localWriteB_0_0_0_0 + 0) = b_0_0_0_0;
#pragma clang diagnostic pop


    __syncthreads(); //




    /* iter 0 (reset local read pointers iteration)  (swap and reset local write pointers iteration)  (swap local read pointers iteration)  */


    /* local read a */
    rA[0*VECTOR_WIDTH+0] = localReadA[0*SG0I*VECTOR_WIDTH + 0]; 
    rA[0*VECTOR_WIDTH+1] = localReadA[0*SG0I*VECTOR_WIDTH + 1]; 
    rA[0*VECTOR_WIDTH+2] = localReadA[0*SG0I*VECTOR_WIDTH + 2]; 
    rA[0*VECTOR_WIDTH+3] = localReadA[0*SG0I*VECTOR_WIDTH + 3]; 
    rA[1*VECTOR_WIDTH+0] = localReadA[1*SG0I*VECTOR_WIDTH + 0]; 
    rA[1*VECTOR_WIDTH+1] = localReadA[1*SG0I*VECTOR_WIDTH + 1]; 
    rA[1*VECTOR_WIDTH+2] = localReadA[1*SG0I*VECTOR_WIDTH + 2]; 
    rA[1*VECTOR_WIDTH+3] = localReadA[1*SG0I*VECTOR_WIDTH + 3]; 

    /* local read b */
    rB[0*VECTOR_WIDTH+0] = localReadB[0*SG1J*VECTOR_WIDTH + 0]; 
    rB[0*VECTOR_WIDTH+1] = localReadB[0*SG1J*VECTOR_WIDTH + 1]; 
    rB[0*VECTOR_WIDTH+2] = localReadB[0*SG1J*VECTOR_WIDTH + 2]; 
    rB[0*VECTOR_WIDTH+3] = localReadB[0*SG1J*VECTOR_WIDTH + 3]; 
    rB[1*VECTOR_WIDTH+0] = localReadB[1*SG1J*VECTOR_WIDTH + 0]; 
    rB[1*VECTOR_WIDTH+1] = localReadB[1*SG1J*VECTOR_WIDTH + 1]; 
    rB[1*VECTOR_WIDTH+2] = localReadB[1*SG1J*VECTOR_WIDTH + 2]; 
    rB[1*VECTOR_WIDTH+3] = localReadB[1*SG1J*VECTOR_WIDTH + 3]; 

    /* local read init pointers a */
    localReadA = (DATA_TYPE *)(localMemory + localReadOffsetA);

    /* local read init pointers b */
    localReadB = (DATA_TYPE *)(localMemory + localReadOffsetB);
    MAC_8x8




    /******************************************/
    /* Unrolled Loop - End                    */
    /******************************************/

  }


  /* Before NLL: Check VGPR.checkin for INT8 LW */


  /******************************************/
  /* Tail Loop                              */
  /******************************************/


  /* Compute tail loop num iter */
  numIterK = (((sizeK % LOCAL_DEPTHU) + LOCAL_SPLITU - 1) / LOCAL_SPLITU);


  /* remove stagger offsets for tail loop */

  globalReadA_0_0_0_0 += ((origNumIter - (staggerUIter - 0)) * globalReadIncAK); // remove stagger offset

  globalReadB_0_0_0_0 += ((origNumIter - (staggerUIter - 0)) * globalReadIncBK); // remove stagger offset


  /* Update M0 for DTLDS */



  /* global read a */


  /* global read A */
  a_0_0_0_0 = ( globalReadOffsetAK_0_0  + 0 >= (sizeK % LOCAL_DEPTHU) ) ? SCALAR_OOB_DATA : *(globalReadA_0_0_0_0 + 0);


  /* Update M0 for DTLDS */



  /* global read b */


  /* global read B */
  b_0_0_0_0 = ( globalReadOffsetBK_0_0  + 0 >= (sizeK % LOCAL_DEPTHU) ) ? SCALAR_OOB_DATA : *(globalReadB_0_0_0_0 + 0);


  __syncthreads(); //



  /* local write init pointers A */
  localWriteA_0_0_0_0 = (DATA_TYPE *)(localMemory + localWriteOffsetA_0_0_0_0);


  /* local write init pointers B */
  localWriteB_0_0_0_0 = (DATA_TYPE *)(localMemory + localWriteOffsetB_0_0_0_0);


  /* local write a */

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wconditional-uninitialized"
  *(localWriteA_0_0_0_0 + 0) = a_0_0_0_0;
#pragma clang diagnostic pop


  /* local write b */

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wconditional-uninitialized"
  *(localWriteB_0_0_0_0 + 0) = b_0_0_0_0;
#pragma clang diagnostic pop


  /* Recalc local read offsets */



  __syncthreads(); //


  /* tail loop: macs */

  while (numIterK-- > 0) {


    /* local read a */

    rA[0*VECTOR_WIDTH+0] = localReadA[0*SG0I*VECTOR_WIDTH + 0]; 
    rA[0*VECTOR_WIDTH+1] = localReadA[0*SG0I*VECTOR_WIDTH + 1]; 
    rA[0*VECTOR_WIDTH+2] = localReadA[0*SG0I*VECTOR_WIDTH + 2]; 
    rA[0*VECTOR_WIDTH+3] = localReadA[0*SG0I*VECTOR_WIDTH + 3]; 
    rA[1*VECTOR_WIDTH+0] = localReadA[1*SG0I*VECTOR_WIDTH + 0]; 
    rA[1*VECTOR_WIDTH+1] = localReadA[1*SG0I*VECTOR_WIDTH + 1]; 
    rA[1*VECTOR_WIDTH+2] = localReadA[1*SG0I*VECTOR_WIDTH + 2]; 
    rA[1*VECTOR_WIDTH+3] = localReadA[1*SG0I*VECTOR_WIDTH + 3]; 


    /* local read b */

    rB[0*VECTOR_WIDTH+0] = localReadB[0*SG1J*VECTOR_WIDTH + 0]; 
    rB[0*VECTOR_WIDTH+1] = localReadB[0*SG1J*VECTOR_WIDTH + 1]; 
    rB[0*VECTOR_WIDTH+2] = localReadB[0*SG1J*VECTOR_WIDTH + 2]; 
    rB[0*VECTOR_WIDTH+3] = localReadB[0*SG1J*VECTOR_WIDTH + 3]; 
    rB[1*VECTOR_WIDTH+0] = localReadB[1*SG1J*VECTOR_WIDTH + 0]; 
    rB[1*VECTOR_WIDTH+1] = localReadB[1*SG1J*VECTOR_WIDTH + 1]; 
    rB[1*VECTOR_WIDTH+2] = localReadB[1*SG1J*VECTOR_WIDTH + 2]; 
    rB[1*VECTOR_WIDTH+3] = localReadB[1*SG1J*VECTOR_WIDTH + 3]; 


    /* local read inc a */

    localReadA += LOCAL_SPLITU*(MT0I+PAD);


    /* local read inc b */

    localReadB += LOCAL_SPLITU*(MT1J+PAD);


    MAC_8x8

  }






  /******************************************/
  /* LocalSplitU Reduction                  */
  /******************************************/

  __syncthreads(); //


  /* LocalSplitU: local write */

  COMPUTE_DATA_TYPE *localLocalSplitU = (COMPUTE_DATA_TYPE *)(localMemory);
  localLocalSplitU[0 + (lr0I + 0*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 0 + SG1J*VECTOR_WIDTH*0) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[0 + (0+0*(TT0I/VECTOR_WIDTH)+0*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[1 + (lr0I + 0*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 0 + SG1J*VECTOR_WIDTH*0) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[1 + (0+0*(TT0I/VECTOR_WIDTH)+0*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[2 + (lr0I + 0*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 0 + SG1J*VECTOR_WIDTH*0) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[2 + (0+0*(TT0I/VECTOR_WIDTH)+0*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[3 + (lr0I + 0*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 0 + SG1J*VECTOR_WIDTH*0) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[3 + (0+0*(TT0I/VECTOR_WIDTH)+0*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[0 + (lr0I + 0*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 1 + SG1J*VECTOR_WIDTH*0) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[0 + (0+1*(TT0I/VECTOR_WIDTH)+0*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[1 + (lr0I + 0*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 1 + SG1J*VECTOR_WIDTH*0) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[1 + (0+1*(TT0I/VECTOR_WIDTH)+0*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[2 + (lr0I + 0*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 1 + SG1J*VECTOR_WIDTH*0) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[2 + (0+1*(TT0I/VECTOR_WIDTH)+0*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[3 + (lr0I + 0*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 1 + SG1J*VECTOR_WIDTH*0) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[3 + (0+1*(TT0I/VECTOR_WIDTH)+0*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[0 + (lr0I + 0*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 2 + SG1J*VECTOR_WIDTH*0) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[0 + (0+2*(TT0I/VECTOR_WIDTH)+0*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[1 + (lr0I + 0*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 2 + SG1J*VECTOR_WIDTH*0) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[1 + (0+2*(TT0I/VECTOR_WIDTH)+0*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[2 + (lr0I + 0*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 2 + SG1J*VECTOR_WIDTH*0) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[2 + (0+2*(TT0I/VECTOR_WIDTH)+0*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[3 + (lr0I + 0*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 2 + SG1J*VECTOR_WIDTH*0) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[3 + (0+2*(TT0I/VECTOR_WIDTH)+0*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[0 + (lr0I + 0*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 3 + SG1J*VECTOR_WIDTH*0) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[0 + (0+3*(TT0I/VECTOR_WIDTH)+0*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[1 + (lr0I + 0*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 3 + SG1J*VECTOR_WIDTH*0) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[1 + (0+3*(TT0I/VECTOR_WIDTH)+0*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[2 + (lr0I + 0*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 3 + SG1J*VECTOR_WIDTH*0) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[2 + (0+3*(TT0I/VECTOR_WIDTH)+0*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[3 + (lr0I + 0*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 3 + SG1J*VECTOR_WIDTH*0) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[3 + (0+3*(TT0I/VECTOR_WIDTH)+0*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[0 + (lr0I + 1*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 0 + SG1J*VECTOR_WIDTH*0) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[0 + (1+0*(TT0I/VECTOR_WIDTH)+0*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[1 + (lr0I + 1*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 0 + SG1J*VECTOR_WIDTH*0) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[1 + (1+0*(TT0I/VECTOR_WIDTH)+0*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[2 + (lr0I + 1*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 0 + SG1J*VECTOR_WIDTH*0) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[2 + (1+0*(TT0I/VECTOR_WIDTH)+0*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[3 + (lr0I + 1*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 0 + SG1J*VECTOR_WIDTH*0) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[3 + (1+0*(TT0I/VECTOR_WIDTH)+0*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[0 + (lr0I + 1*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 1 + SG1J*VECTOR_WIDTH*0) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[0 + (1+1*(TT0I/VECTOR_WIDTH)+0*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[1 + (lr0I + 1*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 1 + SG1J*VECTOR_WIDTH*0) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[1 + (1+1*(TT0I/VECTOR_WIDTH)+0*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[2 + (lr0I + 1*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 1 + SG1J*VECTOR_WIDTH*0) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[2 + (1+1*(TT0I/VECTOR_WIDTH)+0*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[3 + (lr0I + 1*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 1 + SG1J*VECTOR_WIDTH*0) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[3 + (1+1*(TT0I/VECTOR_WIDTH)+0*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[0 + (lr0I + 1*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 2 + SG1J*VECTOR_WIDTH*0) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[0 + (1+2*(TT0I/VECTOR_WIDTH)+0*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[1 + (lr0I + 1*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 2 + SG1J*VECTOR_WIDTH*0) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[1 + (1+2*(TT0I/VECTOR_WIDTH)+0*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[2 + (lr0I + 1*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 2 + SG1J*VECTOR_WIDTH*0) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[2 + (1+2*(TT0I/VECTOR_WIDTH)+0*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[3 + (lr0I + 1*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 2 + SG1J*VECTOR_WIDTH*0) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[3 + (1+2*(TT0I/VECTOR_WIDTH)+0*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[0 + (lr0I + 1*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 3 + SG1J*VECTOR_WIDTH*0) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[0 + (1+3*(TT0I/VECTOR_WIDTH)+0*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[1 + (lr0I + 1*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 3 + SG1J*VECTOR_WIDTH*0) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[1 + (1+3*(TT0I/VECTOR_WIDTH)+0*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[2 + (lr0I + 1*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 3 + SG1J*VECTOR_WIDTH*0) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[2 + (1+3*(TT0I/VECTOR_WIDTH)+0*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[3 + (lr0I + 1*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 3 + SG1J*VECTOR_WIDTH*0) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[3 + (1+3*(TT0I/VECTOR_WIDTH)+0*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[0 + (lr0I + 0*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 0 + SG1J*VECTOR_WIDTH*1) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[0 + (0+0*(TT0I/VECTOR_WIDTH)+1*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[1 + (lr0I + 0*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 0 + SG1J*VECTOR_WIDTH*1) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[1 + (0+0*(TT0I/VECTOR_WIDTH)+1*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[2 + (lr0I + 0*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 0 + SG1J*VECTOR_WIDTH*1) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[2 + (0+0*(TT0I/VECTOR_WIDTH)+1*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[3 + (lr0I + 0*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 0 + SG1J*VECTOR_WIDTH*1) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[3 + (0+0*(TT0I/VECTOR_WIDTH)+1*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[0 + (lr0I + 0*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 1 + SG1J*VECTOR_WIDTH*1) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[0 + (0+1*(TT0I/VECTOR_WIDTH)+1*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[1 + (lr0I + 0*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 1 + SG1J*VECTOR_WIDTH*1) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[1 + (0+1*(TT0I/VECTOR_WIDTH)+1*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[2 + (lr0I + 0*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 1 + SG1J*VECTOR_WIDTH*1) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[2 + (0+1*(TT0I/VECTOR_WIDTH)+1*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[3 + (lr0I + 0*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 1 + SG1J*VECTOR_WIDTH*1) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[3 + (0+1*(TT0I/VECTOR_WIDTH)+1*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[0 + (lr0I + 0*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 2 + SG1J*VECTOR_WIDTH*1) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[0 + (0+2*(TT0I/VECTOR_WIDTH)+1*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[1 + (lr0I + 0*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 2 + SG1J*VECTOR_WIDTH*1) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[1 + (0+2*(TT0I/VECTOR_WIDTH)+1*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[2 + (lr0I + 0*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 2 + SG1J*VECTOR_WIDTH*1) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[2 + (0+2*(TT0I/VECTOR_WIDTH)+1*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[3 + (lr0I + 0*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 2 + SG1J*VECTOR_WIDTH*1) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[3 + (0+2*(TT0I/VECTOR_WIDTH)+1*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[0 + (lr0I + 0*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 3 + SG1J*VECTOR_WIDTH*1) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[0 + (0+3*(TT0I/VECTOR_WIDTH)+1*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[1 + (lr0I + 0*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 3 + SG1J*VECTOR_WIDTH*1) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[1 + (0+3*(TT0I/VECTOR_WIDTH)+1*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[2 + (lr0I + 0*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 3 + SG1J*VECTOR_WIDTH*1) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[2 + (0+3*(TT0I/VECTOR_WIDTH)+1*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[3 + (lr0I + 0*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 3 + SG1J*VECTOR_WIDTH*1) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[3 + (0+3*(TT0I/VECTOR_WIDTH)+1*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[0 + (lr0I + 1*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 0 + SG1J*VECTOR_WIDTH*1) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[0 + (1+0*(TT0I/VECTOR_WIDTH)+1*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[1 + (lr0I + 1*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 0 + SG1J*VECTOR_WIDTH*1) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[1 + (1+0*(TT0I/VECTOR_WIDTH)+1*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[2 + (lr0I + 1*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 0 + SG1J*VECTOR_WIDTH*1) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[2 + (1+0*(TT0I/VECTOR_WIDTH)+1*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[3 + (lr0I + 1*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 0 + SG1J*VECTOR_WIDTH*1) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[3 + (1+0*(TT0I/VECTOR_WIDTH)+1*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[0 + (lr0I + 1*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 1 + SG1J*VECTOR_WIDTH*1) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[0 + (1+1*(TT0I/VECTOR_WIDTH)+1*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[1 + (lr0I + 1*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 1 + SG1J*VECTOR_WIDTH*1) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[1 + (1+1*(TT0I/VECTOR_WIDTH)+1*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[2 + (lr0I + 1*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 1 + SG1J*VECTOR_WIDTH*1) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[2 + (1+1*(TT0I/VECTOR_WIDTH)+1*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[3 + (lr0I + 1*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 1 + SG1J*VECTOR_WIDTH*1) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[3 + (1+1*(TT0I/VECTOR_WIDTH)+1*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[0 + (lr0I + 1*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 2 + SG1J*VECTOR_WIDTH*1) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[0 + (1+2*(TT0I/VECTOR_WIDTH)+1*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[1 + (lr0I + 1*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 2 + SG1J*VECTOR_WIDTH*1) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[1 + (1+2*(TT0I/VECTOR_WIDTH)+1*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[2 + (lr0I + 1*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 2 + SG1J*VECTOR_WIDTH*1) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[2 + (1+2*(TT0I/VECTOR_WIDTH)+1*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[3 + (lr0I + 1*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 2 + SG1J*VECTOR_WIDTH*1) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[3 + (1+2*(TT0I/VECTOR_WIDTH)+1*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[0 + (lr0I + 1*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 3 + SG1J*VECTOR_WIDTH*1) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[0 + (1+3*(TT0I/VECTOR_WIDTH)+1*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[1 + (lr0I + 1*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 3 + SG1J*VECTOR_WIDTH*1) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[1 + (1+3*(TT0I/VECTOR_WIDTH)+1*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[2 + (lr0I + 1*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 3 + SG1J*VECTOR_WIDTH*1) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[2 + (1+3*(TT0I/VECTOR_WIDTH)+1*TT0I)*VECTOR_WIDTH];
  localLocalSplitU[3 + (lr0I + 1*SG0I + (MT0I/VECTOR_WIDTH)*(lr1J*VECTOR_WIDTH + 3 + SG1J*VECTOR_WIDTH*1) + (MT0I*MT1J/VECTOR_WIDTH)*sgId)*VECTOR_WIDTH] = rC[3 + (1+3*(TT0I/VECTOR_WIDTH)+1*TT0I)*VECTOR_WIDTH];
  __syncthreads(); //


  /* LocalSplitU: local read */

  rC[0 +   0*GLOBAL_WRITE_VECTOR_WIDTH] = localLocalSplitU[0 + (serial+0*NUM_THREADS)*GLOBAL_WRITE_VECTOR_WIDTH];
  rC[1 +   0*GLOBAL_WRITE_VECTOR_WIDTH] = localLocalSplitU[1 + (serial+0*NUM_THREADS)*GLOBAL_WRITE_VECTOR_WIDTH];
  rC[2 +   0*GLOBAL_WRITE_VECTOR_WIDTH] = localLocalSplitU[2 + (serial+0*NUM_THREADS)*GLOBAL_WRITE_VECTOR_WIDTH];
  rC[3 +   0*GLOBAL_WRITE_VECTOR_WIDTH] = localLocalSplitU[3 + (serial+0*NUM_THREADS)*GLOBAL_WRITE_VECTOR_WIDTH];
  rC[0 +   1*GLOBAL_WRITE_VECTOR_WIDTH] = localLocalSplitU[0 + (serial+1*NUM_THREADS)*GLOBAL_WRITE_VECTOR_WIDTH];
  rC[1 +   1*GLOBAL_WRITE_VECTOR_WIDTH] = localLocalSplitU[1 + (serial+1*NUM_THREADS)*GLOBAL_WRITE_VECTOR_WIDTH];
  rC[2 +   1*GLOBAL_WRITE_VECTOR_WIDTH] = localLocalSplitU[2 + (serial+1*NUM_THREADS)*GLOBAL_WRITE_VECTOR_WIDTH];
  rC[3 +   1*GLOBAL_WRITE_VECTOR_WIDTH] = localLocalSplitU[3 + (serial+1*NUM_THREADS)*GLOBAL_WRITE_VECTOR_WIDTH];
  rC[0 +   2*GLOBAL_WRITE_VECTOR_WIDTH] = localLocalSplitU[0 + (serial+2*NUM_THREADS)*GLOBAL_WRITE_VECTOR_WIDTH];
  rC[1 +   2*GLOBAL_WRITE_VECTOR_WIDTH] = localLocalSplitU[1 + (serial+2*NUM_THREADS)*GLOBAL_WRITE_VECTOR_WIDTH];
  rC[2 +   2*GLOBAL_WRITE_VECTOR_WIDTH] = localLocalSplitU[2 + (serial+2*NUM_THREADS)*GLOBAL_WRITE_VECTOR_WIDTH];
  rC[3 +   2*GLOBAL_WRITE_VECTOR_WIDTH] = localLocalSplitU[3 + (serial+2*NUM_THREADS)*GLOBAL_WRITE_VECTOR_WIDTH];
  rC[0 +   3*GLOBAL_WRITE_VECTOR_WIDTH] = localLocalSplitU[0 + (serial+3*NUM_THREADS)*GLOBAL_WRITE_VECTOR_WIDTH];
  rC[1 +   3*GLOBAL_WRITE_VECTOR_WIDTH] = localLocalSplitU[1 + (serial+3*NUM_THREADS)*GLOBAL_WRITE_VECTOR_WIDTH];
  rC[2 +   3*GLOBAL_WRITE_VECTOR_WIDTH] = localLocalSplitU[2 + (serial+3*NUM_THREADS)*GLOBAL_WRITE_VECTOR_WIDTH];
  rC[3 +   3*GLOBAL_WRITE_VECTOR_WIDTH] = localLocalSplitU[3 + (serial+3*NUM_THREADS)*GLOBAL_WRITE_VECTOR_WIDTH];



  /* LocalSplitU: reduction */

  rC[0 +   0*GLOBAL_WRITE_VECTOR_WIDTH] += localLocalSplitU[(0 + serial*GLOBAL_WRITE_VECTOR_WIDTH+0*NUM_THREADS*GLOBAL_WRITE_VECTOR_WIDTH + 1*MT0I*MT1J)];
  rC[1 +   0*GLOBAL_WRITE_VECTOR_WIDTH] += localLocalSplitU[(1 + serial*GLOBAL_WRITE_VECTOR_WIDTH+0*NUM_THREADS*GLOBAL_WRITE_VECTOR_WIDTH + 1*MT0I*MT1J)];
  rC[2 +   0*GLOBAL_WRITE_VECTOR_WIDTH] += localLocalSplitU[(2 + serial*GLOBAL_WRITE_VECTOR_WIDTH+0*NUM_THREADS*GLOBAL_WRITE_VECTOR_WIDTH + 1*MT0I*MT1J)];
  rC[3 +   0*GLOBAL_WRITE_VECTOR_WIDTH] += localLocalSplitU[(3 + serial*GLOBAL_WRITE_VECTOR_WIDTH+0*NUM_THREADS*GLOBAL_WRITE_VECTOR_WIDTH + 1*MT0I*MT1J)];
  rC[0 +   1*GLOBAL_WRITE_VECTOR_WIDTH] += localLocalSplitU[(0 + serial*GLOBAL_WRITE_VECTOR_WIDTH+1*NUM_THREADS*GLOBAL_WRITE_VECTOR_WIDTH + 1*MT0I*MT1J)];
  rC[1 +   1*GLOBAL_WRITE_VECTOR_WIDTH] += localLocalSplitU[(1 + serial*GLOBAL_WRITE_VECTOR_WIDTH+1*NUM_THREADS*GLOBAL_WRITE_VECTOR_WIDTH + 1*MT0I*MT1J)];
  rC[2 +   1*GLOBAL_WRITE_VECTOR_WIDTH] += localLocalSplitU[(2 + serial*GLOBAL_WRITE_VECTOR_WIDTH+1*NUM_THREADS*GLOBAL_WRITE_VECTOR_WIDTH + 1*MT0I*MT1J)];
  rC[3 +   1*GLOBAL_WRITE_VECTOR_WIDTH] += localLocalSplitU[(3 + serial*GLOBAL_WRITE_VECTOR_WIDTH+1*NUM_THREADS*GLOBAL_WRITE_VECTOR_WIDTH + 1*MT0I*MT1J)];
  rC[0 +   2*GLOBAL_WRITE_VECTOR_WIDTH] += localLocalSplitU[(0 + serial*GLOBAL_WRITE_VECTOR_WIDTH+2*NUM_THREADS*GLOBAL_WRITE_VECTOR_WIDTH + 1*MT0I*MT1J)];
  rC[1 +   2*GLOBAL_WRITE_VECTOR_WIDTH] += localLocalSplitU[(1 + serial*GLOBAL_WRITE_VECTOR_WIDTH+2*NUM_THREADS*GLOBAL_WRITE_VECTOR_WIDTH + 1*MT0I*MT1J)];
  rC[2 +   2*GLOBAL_WRITE_VECTOR_WIDTH] += localLocalSplitU[(2 + serial*GLOBAL_WRITE_VECTOR_WIDTH+2*NUM_THREADS*GLOBAL_WRITE_VECTOR_WIDTH + 1*MT0I*MT1J)];
  rC[3 +   2*GLOBAL_WRITE_VECTOR_WIDTH] += localLocalSplitU[(3 + serial*GLOBAL_WRITE_VECTOR_WIDTH+2*NUM_THREADS*GLOBAL_WRITE_VECTOR_WIDTH + 1*MT0I*MT1J)];
  rC[0 +   3*GLOBAL_WRITE_VECTOR_WIDTH] += localLocalSplitU[(0 + serial*GLOBAL_WRITE_VECTOR_WIDTH+3*NUM_THREADS*GLOBAL_WRITE_VECTOR_WIDTH + 1*MT0I*MT1J)];
  rC[1 +   3*GLOBAL_WRITE_VECTOR_WIDTH] += localLocalSplitU[(1 + serial*GLOBAL_WRITE_VECTOR_WIDTH+3*NUM_THREADS*GLOBAL_WRITE_VECTOR_WIDTH + 1*MT0I*MT1J)];
  rC[2 +   3*GLOBAL_WRITE_VECTOR_WIDTH] += localLocalSplitU[(2 + serial*GLOBAL_WRITE_VECTOR_WIDTH+3*NUM_THREADS*GLOBAL_WRITE_VECTOR_WIDTH + 1*MT0I*MT1J)];
  rC[3 +   3*GLOBAL_WRITE_VECTOR_WIDTH] += localLocalSplitU[(3 + serial*GLOBAL_WRITE_VECTOR_WIDTH+3*NUM_THREADS*GLOBAL_WRITE_VECTOR_WIDTH + 1*MT0I*MT1J)];

  rC[0 +   0*GLOBAL_WRITE_VECTOR_WIDTH] += localLocalSplitU[(0 + serial*GLOBAL_WRITE_VECTOR_WIDTH+0*NUM_THREADS*GLOBAL_WRITE_VECTOR_WIDTH + 2*MT0I*MT1J)];
  rC[1 +   0*GLOBAL_WRITE_VECTOR_WIDTH] += localLocalSplitU[(1 + serial*GLOBAL_WRITE_VECTOR_WIDTH+0*NUM_THREADS*GLOBAL_WRITE_VECTOR_WIDTH + 2*MT0I*MT1J)];
  rC[2 +   0*GLOBAL_WRITE_VECTOR_WIDTH] += localLocalSplitU[(2 + serial*GLOBAL_WRITE_VECTOR_WIDTH+0*NUM_THREADS*GLOBAL_WRITE_VECTOR_WIDTH + 2*MT0I*MT1J)];
  rC[3 +   0*GLOBAL_WRITE_VECTOR_WIDTH] += localLocalSplitU[(3 + serial*GLOBAL_WRITE_VECTOR_WIDTH+0*NUM_THREADS*GLOBAL_WRITE_VECTOR_WIDTH + 2*MT0I*MT1J)];
  rC[0 +   1*GLOBAL_WRITE_VECTOR_WIDTH] += localLocalSplitU[(0 + serial*GLOBAL_WRITE_VECTOR_WIDTH+1*NUM_THREADS*GLOBAL_WRITE_VECTOR_WIDTH + 2*MT0I*MT1J)];
  rC[1 +   1*GLOBAL_WRITE_VECTOR_WIDTH] += localLocalSplitU[(1 + serial*GLOBAL_WRITE_VECTOR_WIDTH+1*NUM_THREADS*GLOBAL_WRITE_VECTOR_WIDTH + 2*MT0I*MT1J)];
  rC[2 +   1*GLOBAL_WRITE_VECTOR_WIDTH] += localLocalSplitU[(2 + serial*GLOBAL_WRITE_VECTOR_WIDTH+1*NUM_THREADS*GLOBAL_WRITE_VECTOR_WIDTH + 2*MT0I*MT1J)];
  rC[3 +   1*GLOBAL_WRITE_VECTOR_WIDTH] += localLocalSplitU[(3 + serial*GLOBAL_WRITE_VECTOR_WIDTH+1*NUM_THREADS*GLOBAL_WRITE_VECTOR_WIDTH + 2*MT0I*MT1J)];
  rC[0 +   2*GLOBAL_WRITE_VECTOR_WIDTH] += localLocalSplitU[(0 + serial*GLOBAL_WRITE_VECTOR_WIDTH+2*NUM_THREADS*GLOBAL_WRITE_VECTOR_WIDTH + 2*MT0I*MT1J)];
  rC[1 +   2*GLOBAL_WRITE_VECTOR_WIDTH] += localLocalSplitU[(1 + serial*GLOBAL_WRITE_VECTOR_WIDTH+2*NUM_THREADS*GLOBAL_WRITE_VECTOR_WIDTH + 2*MT0I*MT1J)];
  rC[2 +   2*GLOBAL_WRITE_VECTOR_WIDTH] += localLocalSplitU[(2 + serial*GLOBAL_WRITE_VECTOR_WIDTH+2*NUM_THREADS*GLOBAL_WRITE_VECTOR_WIDTH + 2*MT0I*MT1J)];
  rC[3 +   2*GLOBAL_WRITE_VECTOR_WIDTH] += localLocalSplitU[(3 + serial*GLOBAL_WRITE_VECTOR_WIDTH+2*NUM_THREADS*GLOBAL_WRITE_VECTOR_WIDTH + 2*MT0I*MT1J)];
  rC[0 +   3*GLOBAL_WRITE_VECTOR_WIDTH] += localLocalSplitU[(0 + serial*GLOBAL_WRITE_VECTOR_WIDTH+3*NUM_THREADS*GLOBAL_WRITE_VECTOR_WIDTH + 2*MT0I*MT1J)];
  rC[1 +   3*GLOBAL_WRITE_VECTOR_WIDTH] += localLocalSplitU[(1 + serial*GLOBAL_WRITE_VECTOR_WIDTH+3*NUM_THREADS*GLOBAL_WRITE_VECTOR_WIDTH + 2*MT0I*MT1J)];
  rC[2 +   3*GLOBAL_WRITE_VECTOR_WIDTH] += localLocalSplitU[(2 + serial*GLOBAL_WRITE_VECTOR_WIDTH+3*NUM_THREADS*GLOBAL_WRITE_VECTOR_WIDTH + 2*MT0I*MT1J)];
  rC[3 +   3*GLOBAL_WRITE_VECTOR_WIDTH] += localLocalSplitU[(3 + serial*GLOBAL_WRITE_VECTOR_WIDTH+3*NUM_THREADS*GLOBAL_WRITE_VECTOR_WIDTH + 2*MT0I*MT1J)];

  rC[0 +   0*GLOBAL_WRITE_VECTOR_WIDTH] += localLocalSplitU[(0 + serial*GLOBAL_WRITE_VECTOR_WIDTH+0*NUM_THREADS*GLOBAL_WRITE_VECTOR_WIDTH + 3*MT0I*MT1J)];
  rC[1 +   0*GLOBAL_WRITE_VECTOR_WIDTH] += localLocalSplitU[(1 + serial*GLOBAL_WRITE_VECTOR_WIDTH+0*NUM_THREADS*GLOBAL_WRITE_VECTOR_WIDTH + 3*MT0I*MT1J)];
  rC[2 +   0*GLOBAL_WRITE_VECTOR_WIDTH] += localLocalSplitU[(2 + serial*GLOBAL_WRITE_VECTOR_WIDTH+0*NUM_THREADS*GLOBAL_WRITE_VECTOR_WIDTH + 3*MT0I*MT1J)];
  rC[3 +   0*GLOBAL_WRITE_VECTOR_WIDTH] += localLocalSplitU[(3 + serial*GLOBAL_WRITE_VECTOR_WIDTH+0*NUM_THREADS*GLOBAL_WRITE_VECTOR_WIDTH + 3*MT0I*MT1J)];
  rC[0 +   1*GLOBAL_WRITE_VECTOR_WIDTH] += localLocalSplitU[(0 + serial*GLOBAL_WRITE_VECTOR_WIDTH+1*NUM_THREADS*GLOBAL_WRITE_VECTOR_WIDTH + 3*MT0I*MT1J)];
  rC[1 +   1*GLOBAL_WRITE_VECTOR_WIDTH] += localLocalSplitU[(1 + serial*GLOBAL_WRITE_VECTOR_WIDTH+1*NUM_THREADS*GLOBAL_WRITE_VECTOR_WIDTH + 3*MT0I*MT1J)];
  rC[2 +   1*GLOBAL_WRITE_VECTOR_WIDTH] += localLocalSplitU[(2 + serial*GLOBAL_WRITE_VECTOR_WIDTH+1*NUM_THREADS*GLOBAL_WRITE_VECTOR_WIDTH + 3*MT0I*MT1J)];
  rC[3 +   1*GLOBAL_WRITE_VECTOR_WIDTH] += localLocalSplitU[(3 + serial*GLOBAL_WRITE_VECTOR_WIDTH+1*NUM_THREADS*GLOBAL_WRITE_VECTOR_WIDTH + 3*MT0I*MT1J)];
  rC[0 +   2*GLOBAL_WRITE_VECTOR_WIDTH] += localLocalSplitU[(0 + serial*GLOBAL_WRITE_VECTOR_WIDTH+2*NUM_THREADS*GLOBAL_WRITE_VECTOR_WIDTH + 3*MT0I*MT1J)];
  rC[1 +   2*GLOBAL_WRITE_VECTOR_WIDTH] += localLocalSplitU[(1 + serial*GLOBAL_WRITE_VECTOR_WIDTH+2*NUM_THREADS*GLOBAL_WRITE_VECTOR_WIDTH + 3*MT0I*MT1J)];
  rC[2 +   2*GLOBAL_WRITE_VECTOR_WIDTH] += localLocalSplitU[(2 + serial*GLOBAL_WRITE_VECTOR_WIDTH+2*NUM_THREADS*GLOBAL_WRITE_VECTOR_WIDTH + 3*MT0I*MT1J)];
  rC[3 +   2*GLOBAL_WRITE_VECTOR_WIDTH] += localLocalSplitU[(3 + serial*GLOBAL_WRITE_VECTOR_WIDTH+2*NUM_THREADS*GLOBAL_WRITE_VECTOR_WIDTH + 3*MT0I*MT1J)];
  rC[0 +   3*GLOBAL_WRITE_VECTOR_WIDTH] += localLocalSplitU[(0 + serial*GLOBAL_WRITE_VECTOR_WIDTH+3*NUM_THREADS*GLOBAL_WRITE_VECTOR_WIDTH + 3*MT0I*MT1J)];
  rC[1 +   3*GLOBAL_WRITE_VECTOR_WIDTH] += localLocalSplitU[(1 + serial*GLOBAL_WRITE_VECTOR_WIDTH+3*NUM_THREADS*GLOBAL_WRITE_VECTOR_WIDTH + 3*MT0I*MT1J)];
  rC[2 +   3*GLOBAL_WRITE_VECTOR_WIDTH] += localLocalSplitU[(2 + serial*GLOBAL_WRITE_VECTOR_WIDTH+3*NUM_THREADS*GLOBAL_WRITE_VECTOR_WIDTH + 3*MT0I*MT1J)];
  rC[3 +   3*GLOBAL_WRITE_VECTOR_WIDTH] += localLocalSplitU[(3 + serial*GLOBAL_WRITE_VECTOR_WIDTH+3*NUM_THREADS*GLOBAL_WRITE_VECTOR_WIDTH + 3*MT0I*MT1J)];



  /* LocalSplitU: global write indices */

  unsigned int localC0I = (serial % (MT0I/GLOBAL_WRITE_VECTOR_WIDTH))*GLOBAL_WRITE_VECTOR_WIDTH;
  unsigned int globalC0I = (wg0I)*MT0I + localC0I;
  unsigned int flattenedGlobalC0 = globalC0I;
  unsigned int localC1J = serial / (MT0I/GLOBAL_WRITE_VECTOR_WIDTH);
  unsigned int globalC1J = (wg1J)*MT1J + localC1J;
  unsigned int flattenedGlobalC1 = globalC1J;


  /* LocalSplitU: global write */


  /* new 0 offset - inc and extract tensor dims */
  globalC0I =   flattenedGlobalC0 + 0;
  /* new 1 offset - inc and extract tensor dims */
  globalC1J =   flattenedGlobalC1 +  0*CPSV;
  if (flattenedGlobalC0 + 0 < size0I) {  if (flattenedGlobalC1 + 0*CPSV < size1J) {  TYPE_MAC_WRITE( D[ GLOBAL_D( (uint64_t) globalC0I + 0, (uint64_t) globalC1J + 0) ], alpha, rC[0 + 0*GLOBAL_WRITE_VECTOR_WIDTH])} }

  /* new 0 offset - inc and extract tensor dims */
  globalC0I =   flattenedGlobalC0 + 1;
  if (flattenedGlobalC0 + 1 < size0I) {  if (flattenedGlobalC1 + 0*CPSV < size1J) {  TYPE_MAC_WRITE( D[ GLOBAL_D( (uint64_t) globalC0I + 0, (uint64_t) globalC1J + 0) ], alpha, rC[1 + 0*GLOBAL_WRITE_VECTOR_WIDTH])} }

  /* new 0 offset - inc and extract tensor dims */
  globalC0I =   flattenedGlobalC0 + 2;
  if (flattenedGlobalC0 + 2 < size0I) {  if (flattenedGlobalC1 + 0*CPSV < size1J) {  TYPE_MAC_WRITE( D[ GLOBAL_D( (uint64_t) globalC0I + 0, (uint64_t) globalC1J + 0) ], alpha, rC[2 + 0*GLOBAL_WRITE_VECTOR_WIDTH])} }

  /* new 0 offset - inc and extract tensor dims */
  globalC0I =   flattenedGlobalC0 + 3;
  if (flattenedGlobalC0 + 3 < size0I) {  if (flattenedGlobalC1 + 0*CPSV < size1J) {  TYPE_MAC_WRITE( D[ GLOBAL_D( (uint64_t) globalC0I + 0, (uint64_t) globalC1J + 0) ], alpha, rC[3 + 0*GLOBAL_WRITE_VECTOR_WIDTH])} }

  /* new 0 offset - inc and extract tensor dims */
  globalC0I =   flattenedGlobalC0 + 0;
  /* new 1 offset - inc and extract tensor dims */
  globalC1J =   flattenedGlobalC1 +  1*CPSV;
  if (flattenedGlobalC0 + 0 < size0I) {  if (flattenedGlobalC1 + 1*CPSV < size1J) {  TYPE_MAC_WRITE( D[ GLOBAL_D( (uint64_t) globalC0I + 0, (uint64_t) globalC1J + 0) ], alpha, rC[0 + 1*GLOBAL_WRITE_VECTOR_WIDTH])} }

  /* new 0 offset - inc and extract tensor dims */
  globalC0I =   flattenedGlobalC0 + 1;
  if (flattenedGlobalC0 + 1 < size0I) {  if (flattenedGlobalC1 + 1*CPSV < size1J) {  TYPE_MAC_WRITE( D[ GLOBAL_D( (uint64_t) globalC0I + 0, (uint64_t) globalC1J + 0) ], alpha, rC[1 + 1*GLOBAL_WRITE_VECTOR_WIDTH])} }

  /* new 0 offset - inc and extract tensor dims */
  globalC0I =   flattenedGlobalC0 + 2;
  if (flattenedGlobalC0 + 2 < size0I) {  if (flattenedGlobalC1 + 1*CPSV < size1J) {  TYPE_MAC_WRITE( D[ GLOBAL_D( (uint64_t) globalC0I + 0, (uint64_t) globalC1J + 0) ], alpha, rC[2 + 1*GLOBAL_WRITE_VECTOR_WIDTH])} }

  /* new 0 offset - inc and extract tensor dims */
  globalC0I =   flattenedGlobalC0 + 3;
  if (flattenedGlobalC0 + 3 < size0I) {  if (flattenedGlobalC1 + 1*CPSV < size1J) {  TYPE_MAC_WRITE( D[ GLOBAL_D( (uint64_t) globalC0I + 0, (uint64_t) globalC1J + 0) ], alpha, rC[3 + 1*GLOBAL_WRITE_VECTOR_WIDTH])} }

  /* new 0 offset - inc and extract tensor dims */
  globalC0I =   flattenedGlobalC0 + 0;
  /* new 1 offset - inc and extract tensor dims */
  globalC1J =   flattenedGlobalC1 +  2*CPSV;
  if (flattenedGlobalC0 + 0 < size0I) {  if (flattenedGlobalC1 + 2*CPSV < size1J) {  TYPE_MAC_WRITE( D[ GLOBAL_D( (uint64_t) globalC0I + 0, (uint64_t) globalC1J + 0) ], alpha, rC[0 + 2*GLOBAL_WRITE_VECTOR_WIDTH])} }

  /* new 0 offset - inc and extract tensor dims */
  globalC0I =   flattenedGlobalC0 + 1;
  if (flattenedGlobalC0 + 1 < size0I) {  if (flattenedGlobalC1 + 2*CPSV < size1J) {  TYPE_MAC_WRITE( D[ GLOBAL_D( (uint64_t) globalC0I + 0, (uint64_t) globalC1J + 0) ], alpha, rC[1 + 2*GLOBAL_WRITE_VECTOR_WIDTH])} }

  /* new 0 offset - inc and extract tensor dims */
  globalC0I =   flattenedGlobalC0 + 2;
  if (flattenedGlobalC0 + 2 < size0I) {  if (flattenedGlobalC1 + 2*CPSV < size1J) {  TYPE_MAC_WRITE( D[ GLOBAL_D( (uint64_t) globalC0I + 0, (uint64_t) globalC1J + 0) ], alpha, rC[2 + 2*GLOBAL_WRITE_VECTOR_WIDTH])} }

  /* new 0 offset - inc and extract tensor dims */
  globalC0I =   flattenedGlobalC0 + 3;
  if (flattenedGlobalC0 + 3 < size0I) {  if (flattenedGlobalC1 + 2*CPSV < size1J) {  TYPE_MAC_WRITE( D[ GLOBAL_D( (uint64_t) globalC0I + 0, (uint64_t) globalC1J + 0) ], alpha, rC[3 + 2*GLOBAL_WRITE_VECTOR_WIDTH])} }

  /* new 0 offset - inc and extract tensor dims */
  globalC0I =   flattenedGlobalC0 + 0;
  /* new 1 offset - inc and extract tensor dims */
  globalC1J =   flattenedGlobalC1 +  3*CPSV;
  if (flattenedGlobalC0 + 0 < size0I) {  if (flattenedGlobalC1 + 3*CPSV < size1J) {  TYPE_MAC_WRITE( D[ GLOBAL_D( (uint64_t) globalC0I + 0, (uint64_t) globalC1J + 0) ], alpha, rC[0 + 3*GLOBAL_WRITE_VECTOR_WIDTH])} }

  /* new 0 offset - inc and extract tensor dims */
  globalC0I =   flattenedGlobalC0 + 1;
  if (flattenedGlobalC0 + 1 < size0I) {  if (flattenedGlobalC1 + 3*CPSV < size1J) {  TYPE_MAC_WRITE( D[ GLOBAL_D( (uint64_t) globalC0I + 0, (uint64_t) globalC1J + 0) ], alpha, rC[1 + 3*GLOBAL_WRITE_VECTOR_WIDTH])} }

  /* new 0 offset - inc and extract tensor dims */
  globalC0I =   flattenedGlobalC0 + 2;
  if (flattenedGlobalC0 + 2 < size0I) {  if (flattenedGlobalC1 + 3*CPSV < size1J) {  TYPE_MAC_WRITE( D[ GLOBAL_D( (uint64_t) globalC0I + 0, (uint64_t) globalC1J + 0) ], alpha, rC[2 + 3*GLOBAL_WRITE_VECTOR_WIDTH])} }

  /* new 0 offset - inc and extract tensor dims */
  globalC0I =   flattenedGlobalC0 + 3;
  if (flattenedGlobalC0 + 3 < size0I) {  if (flattenedGlobalC1 + 3*CPSV < size1J) {  TYPE_MAC_WRITE( D[ GLOBAL_D( (uint64_t) globalC0I + 0, (uint64_t) globalC1J + 0) ], alpha, rC[3 + 3*GLOBAL_WRITE_VECTOR_WIDTH])} }


}



